# Taller Básico de Python — Variables, Tipos, Operadores y Diccionarios

**Temas:** Variables · Tipos de datos · Operadores aritméticos · Operadores de comparación · Operadores lógicos · Diccionarios

Resuelve cada ejercicio en la celda de código correspondiente.

---
## Ejercicio 1 — Variables básicas
Crea tres variables: `nombre` (tu nombre), `edad` (un número entero) y `ciudad` (una ciudad).  
Imprímelas en una sola línea con el formato:  
`Hola, soy Ana, tengo 20 años y vivo en Bogotá`

In [ ]:
nombre : 'Cristian'
edad : 26
ciudad : 'Cali'

print (f"Hola soy {nombre} tengo {edad} y vivo en {ciudad}")

Hola soy Cristian tengo 26 y vivo en Cali

---
## Ejercicio 2 — Tipos de datos
Crea una variable de cada uno de estos tipos: `int`, `float`, `str`, `bool`.  
Usa `type()` para imprimir el tipo de cada una y verifica que sean correctos.

In [ ]:
# Tu solución aquí

---
## Ejercicio 3 — Operadores aritméticos
Dadas las variables `a = 18` y `b = 5`, calcula e imprime:
1. La suma
2. La resta
3. La multiplicación
4. La división exacta
5. La división entera
6. El residuo (módulo)
7. `a` elevado a la potencia `b`

In [ ]:
a = 18
b = 5
# Tu solución aquí

---
## Ejercicio 4 — Intercambio de variables
Dadas las variables `x = 10` y `y = 25`, intercambia sus valores **sin usar una variable auxiliar**.  
Imprime los valores antes y después del intercambio.

In [ ]:
x = 10
y = 25
# Tu solución aquí

---
## Ejercicio 5 — Operadores de comparación
Dadas las variables `p = 40` y `q = 40`, evalúa y muestra el resultado de:
1. `p > q`
2. `p >= q`
3. `p == q`
4. `p != q`
5. `p < q`

¿Qué tipo devuelve cada expresión? Compruébalo con `type()`.

In [ ]:
p = 40
q = 40

print (p > q)
print(type(p > q))

print(p >= q)
print(type(p >= q))

print( p == q)
print(type(p == q))

print(p != q)
print(type(p != q))

print(p < q)
print(type(p < q))

False
<class 'bool'>
True
<class 'bool'>
True
<class 'bool'>
False
<class 'bool'>
False
<class 'bool'>

---
## Ejercicio 6 — Operadores lógicos `and` / `or` / `not`
Usando `edad = 17` y `tiene_permiso = True`, determina con operadores lógicos si la persona:
1. Puede entrar sola (mayor de edad **y** con permiso).
2. Puede entrar de alguna forma (mayor de edad **o** con permiso).
3. **No** tiene permiso.

Imprime cada resultado como `True` o `False`.

In [ ]:
edad = 17
tiene_permiso = True
# Tu solución aquí
if edad >= 18 and tiene_permiso == True:
  print('Puede entrar sola')

if edad >= 18 or tiene_permiso == True:
  print('Puede entrar de alguna forma')

else:
  print('No tiene permiso')

Puede entrar de alguna forma

---
## Ejercicio 7 — Condiciones combinadas
Una tienda hace descuento si el cliente es socio **o** si la compra supera $100,  
**y además** el día es fin de semana.

Usa las variables: `es_socio = False`, `total_compra = 120`, `es_fin_de_semana = True`.  
Calcula si aplica el descuento e imprime `"Descuento aplicado"` o `"Sin descuento"`.

In [ ]:
from ast import TypeAlias
es_socio = False
total_compra = 120
es_fin_de_semana = True
# Tu solución aquí

if es_socio == True or (total_compra > 100 and es_fin_de_semana == True):
  print('Descuento aplicado')
else:
  print('Sin descuento')

Descuento aplicado

---
## Ejercicio 8 — Diccionario: creación y acceso
Crea un diccionario `persona` con las llaves: `nombre`, `edad`, `ciudad` y `activo`.  
1. Imprime el valor de `nombre` y `edad`.
2. Cambia `edad` a un valor diferente y vuelve a imprimirla.
3. Agrega la llave `correo` con cualquier dirección de email.
4. Elimina la llave `activo` usando `del`.
5. Imprime cuántas llaves tiene el diccionario con `len()`.

In [ ]:
persona = {"nombre": "Ana", "edad": 20, "ciudad": "Bogotá", "activo": True}
# Tu solución aquí
print(persona['nombre'])
print(persona ['edad'])
print(f'La persona se llama {persona['nombre']} y tiene {persona['edad']} años')

persona ['edad'] = 30

persona ['correo'] = 'melanyalejandra0721@gmail.com'

del persona["activo"]

print(len(persona))

print(persona)

Ana
20
La persona se llama Ana y tiene 20 años
4
{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Bogotá', 'correo': 'melanyalejandra0721@gmail.com'}

---
## Ejercicio 9 — Métodos de diccionario
```python
notas = {"matematicas": 85, "python": 92, "ingles": 78, "historia": 70}
```
1. Imprime todas las llaves con `.keys()`.
2. Imprime todos los valores con `.values()`.
3. Usa `.get("fisica", 0)` — ¿qué devuelve y por qué?
4. Usa `.get("python")` — ¿qué devuelve?
5. Imprime los pares llave-valor con `.items()`.
6. ¿`notas["python"] > notas["historia"]`?

In [ ]:
notas = {"matematicas": 85, "python": 92, "ingles": 78, "historia": 70}
# Tu solución aquí

llaves = list (notas.keys())
print(llaves)

valores = list(notas.values())
print(valores)

print(notas.get("fisica", 0))

print(notas.get("python"))

pares = list(notas.items())
print(pares

dict_keys(['matematicas', 'python', 'ingles', 'historia'])
dict_values([85, 92, 78, 70])
0
92
dict_items([('matematicas', 85), ('python', 92), ('ingles', 78), ('historia', 70)])
True

In [ ]:
llaves = list( notas.keys()  )
llaves

['matematicas', 'python', 'ingles', 'historia']

In [ ]:
print(f"Esta es la nota de {llaves[1]} total {notas[llaves[1]]}")

Esta es la nota de python total 92

In [ ]:
for i in range(len(llaves)):
  print (notas[llaves[i]])

85
92
78
70

In [ ]:
for i in range(len(llaves)):
  print (f"Esta es la nota de {llaves[i]} total {notas[llaves[i]]}")

Esta es la nota de matematicas total 85
Esta es la nota de python total 92
Esta es la nota de ingles total 78
Esta es la nota de historia total 70

In [ ]:
list(notas.values())

[85, 92, 78, 70]

In [ ]:
notas.get("ingles"), notas["ingles"], notas.get("matematicas"), notas["matematicas"]

(78, 78, 85, 85)

In [ ]:
print (llaves[0], notas[llaves[0]])

matematicas 85

In [ ]:
for i in range(len(llaves)):
  print(llaves[i], notas.get(llaves[i]))

matematicas 85
python 92
ingles 78
historia 70

In [ ]:
import pandas as pd
todasNotas = [
    {"name": "yusef", "python": 92, "ingles": 78},
    {"name": "cristian", "python": 32, "ingles": 96},
    {"name": "melany", "python": 28, "ingles": 85},
]
df = pd.DataFrame(todasNotas)
df

       name  python  ingles
0     yusef      92      78
1  cristian      32      96
2    melany      28      85

In [ ]:
import pandas as pd2

for i in range(2):
  df2 = pd2.DataFrame(todasNotas)
  print(df2)

       name  python  ingles
0     yusef      92      78
1  cristian      32      96
2    melany      28      85
       name  python  ingles
0     yusef      92      78
1  cristian      32      96
2    melany      28      85

---
## Ejercicio 10 — Diccionario + operadores lógicos
```python
usuario = {"nombre": "Luis", "edad": 19, "suscrito": False, "nivel": "estudiante"}
```
Evalúa y guarda en variables:
1. ¿El usuario es mayor de edad? (`edad >= 18`)
2. ¿Tiene acceso premium? (`suscrito == True`)
3. ¿Puede ver contenido básico? (mayor de edad **o** suscrito)
4. ¿Puede ver contenido premium? (mayor de edad **y** suscrito)
5. ¿La llave `"nivel"` existe **y** su valor es `"admin"`?

Imprime todas las variables.

In [ ]:
usuario = {"nombre": "Luis", "edad": 19, "suscrito": False, "nivel": "estudiante"}
# Tu solución aquí
usuario = {"nombre": "Luis", "edad": 19, "suscrito": False, "nivel": "estudiante"}

usuario = {
    "nombre": "Luis",
    "edad": 19,
    "suscrito": False,
    "nivel": "estudiante"
}

mayor_edad = usuario["edad"] >= 18

acceso_premium = usuario["suscrito"] == True

contenido_basico = mayor_edad or usuario["suscrito"]

contenido_premium = mayor_edad and usuario["suscrito"]

es_admin = "nivel" in usuario and usuario["nivel"] == "admin"

print("¿Es mayor de edad?", mayor_edad)
print("¿Tiene acceso premium?", acceso_premium)
print("¿Puede ver contenido básico?", contenido_basico)
print("¿Puede ver contenido premium?", contenido_premium)
print("¿Es administrador?", es_admin)

¿Es mayor de edad? True
¿Tiene acceso premium? False
¿Puede ver contenido básico? True
¿Puede ver contenido premium? False
¿Es administrador? False

---
## Ejercicio 11 — Cortocircuito lógico
Python evalúa `and` y `or` con cortocircuito.  
Sin ejecutar el código, **predice** qué imprimirá cada línea. Luego ejecútalo y verifica:

```python
print(0 and 5)
print(3 and 7)
print(0 or 9)
print(False or "")
print(not not 42)
```

Escribe tus predicciones como comentarios antes de ejecutar.

In [ ]:
# Predicciones:
# print(0 and 5)      → 0
# print(3 and 7)      → 7
# print(0 or 9)       → 9
# print(False or "") → False
# print(not not 42)   → True

print(0 and 5)
print(3 and 7)
print(0 or 9)
print(False or "")
print(not not 42)

0
7
0

True

---
## Ejercicio 12 — Reto integrador
Construye un mini perfil de estudiante usando solo variables y un diccionario:

1. Define `grado = "10A"`, `materia = "Python"` y `nota_aprobatoria = 60`.
2. Crea un diccionario `estudiante` con las llaves: `nombre`, `nota1`, `nota2`, `nota3`.
3. Calcula el promedio: `(nota1 + nota2 + nota3) / 3` y guárdalo en `promedio`.
4. Determina si aprobó: `promedio >= nota_aprobatoria` y guárdalo en `aprobo`.
5. Determina si tuvo alto rendimiento: promedio >= 80 **y** las tres notas >= 70.
6. Imprime un resumen con todas las variables.

In [ ]:
# Tu solución aquí
grado = "10A"
materia = "Python"
nota_aprobatoria = 60


estudiante = {
    "nombre": "Carlos",
    "nota1": 75,
    "nota2": 88,
    "nota3": 62
}


promedio = (estudiante["nota1"] + estudiante["nota2"] + estudiante["nota3"]) / 3


aprobo = promedio >= nota_aprobatoria


alto_rendimiento = (promedio) >= 80 and \
                   (estudiante["nota1"] >= 70) and \
                   (estudiante["nota2"] >= 70) and \
                   (estudiante["nota3"] >= 70)


print(f"******* Resumen del Estudiante ********")
print(f"Grado: {grado}")
print(f"Materia: {materia}")
print(f"Nota Aprobatoria: {nota_aprobatoria}")
print(f"Nombre del Estudiante: {estudiante['nombre']}")
print(f"Notas: {estudiante['nota1']}, {estudiante['nota2']}, {estudiante['nota3']}")
print(f"Promedio: {promedio:.2f}")
print(f"Aprobado: {aprobo}")
print(f"Alto Rendimiento: {alto_rendimiento}")
print(f"******************************************")

******* Resumen del Estudiante ********
Grado: 10A
Materia: Python
Nota Aprobatoria: 60
Nombre del Estudiante: Carlos
Notas: 75, 88, 62
Promedio: 75.00
Aprobado: True
Alto Rendimiento: False
******************************************

In [ ]:
from random import randint
#datos
import pandas as pd

totalPedidos = []

productos = [
    {"productos": "Combo", "tiempo": 4},
    {"productos": "Boxes", "tiempo": 3},
    {"productos": "PopCorn", "tiempo": 6},
    {"productos": "Hamburguesa", "tiempo": 4}
]
empleados = [
    {"nombre": "Melany"},
    {"nombre": "Wanda"},
    {"nombre": "Cataleya"},
    {"nombre": "Yusef"},
    {"nombre": "Sara"},
]


pedidos = []
for i in range(300):
  producto = productos[randint(0, 3)]
  empleado = empleados[i % len(empleados)]["nombre"]
  pedidos.append({
      "empleado": empleado,
      "producto": producto["productos"],
      "tiempo": producto["tiempo"],
      "timeradd": producto["tiempo"] + randint(1, 10)
  })


df = pd.DataFrame(pedidos)
df

     empleado     producto  tiempo  timeradd
0      Melany        Boxes       3        12
1       Wanda        Boxes       3         6
2    Cataleya        Boxes       3         6
3       Yusef        Boxes       3         8
4        Sara  Hamburguesa       4         7
..        ...          ...     ...       ...
295    Melany      PopCorn       6        11
296     Wanda        Combo       4         9
297  Cataleya        Combo       4         6
298     Yusef        Boxes       3         5
299      Sara        Boxes       3        12

[300 rows x 4 columns]

In [ ]:
mela = 0
wanda = 0
cataleya = 0
sara = 0
yusef = 0

total = {}
for i in pedidos:
  if i["empleado"] == "Melany":
     mela += i["timeradd"]
  if i["empleado"] == "Wanda":
     wanda += i["timeradd"]
  if i["empleado"] == "Yusef":
     yusef += i["timeradd"]
  if i["empleado"] == "Cataleya":
     cataleya += i["timeradd"]

  if i["empleado"] == "Sara":
     sara += i["timeradd"]

  total["Wanda"] = wanda / 60
  total["Melany"] = mela / 60
  total["Cataleya"] = cataleya / 60
  total["yusef"] = yusef / 60

  total["sara"] = sara / 60
print(total)

# Obtener la llave con el valor mínimo
empleado_min = min(total, key=total.get)
valor_min = total[empleado_min]

print(f"El más bajo es {empleado_min} con {valor_min:.2f} es la nueva feje")

{'Wanda': 9.75, 'Melany': 9.1, 'Cataleya': 9.483333333333333, 'yusef': 10.616666666666667, 'sara': 9.166666666666666}
El más bajo es Melany con 9.10